

services:
  flowai:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8000:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env.local
    stdin_open: true
    tty: true

  flowai-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    profiles:
      - production